/* Auto-generated by tools/pet-assets/gen_clawd_frames.py ¡ª do not edit. */
#pragma once

#include "pet_bridge.h"
#include "lvgl.h"

#define PET_FRAME_W 270
#define PET_FRAME_H 180
#define PET_MAX_FRAMES 8

typedef struct {
    const lv_image_dsc_t *frames[PET_MAX_FRAMES];
    uint8_t count;
    bool loop;
    uint32_t frame_ms; // 0 = renderer default (150 ms)
} pet_state_anim_t;

extern const pet_state_anim_t pet_anims[PET_STATE_COUNT];
extern const pet_state_anim_t pet_intro_anim; // wake, one-shot
