/* Auto-generated by tools/pet-assets/gen_frames.py — do not edit. */
#pragma once

#include "pet_bridge.h"
#include "lvgl.h"

#define PET_FRAME_W 96
#define PET_FRAME_H 104
#define PET_MAX_FRAMES 4

typedef struct {
    const lv_image_dsc_t *frames[PET_MAX_FRAMES];
    uint8_t count;
    bool loop;
} pet_state_anim_t;

extern const pet_state_anim_t pet_anims[PET_STATE_COUNT];
extern const pet_state_anim_t pet_intro_anim; // waving row, one-shot
