#!/usr/bin/env python3
"""Cut a Codex-pet spritesheet into LVGL C frame arrays for the pet renderer.

Usage: gen_frames.py <spritesheet.webp|png> <output_dir>

Codex pet atlas: 8 columns x 9 rows of 192x208 cells. We keep up to 4
frames per needed row, downscale to 96x104, bake them onto a rounded card
(RGB565 has no alpha, so card corners are flattened against the screen bg).
Output: pet_frames.h + pet_frames.c in <output_dir>.

Swap the spritesheet and re-run to replace the art; the mapping below is
the only part that encodes our display states -> Codex rows.
"""
import sys
from pathlib import Path

from PIL import Image, ImageDraw

CELL_W, CELL_H = 192, 208
GRID_COLS = 8
TARGET_W, TARGET_H = 96, 104
MAX_FRAMES = 4
CARD_COLOR = (0x60, 0x80, 0xFF)   # matches the ticket-01 placeholder card
SCREEN_BG = (0x1A, 0x1A, 0x1A)    # STYLESHEET_DEFAULT_DARK_CORE_DISPLAY_BG_COLOR
CORNER_R = 12

# display state -> (row, loop). Codex rows: 0 idle, 5 failed, 6 waiting,
# 7 running, 8 review. Disconnected is a gray placeholder, no frames.
STATES = [
    ("idle",       0, True),
    ("thinking",   8, True),
    ("working",    7, True),
    ("attention",  6, True),
    ("error",      5, False),  # one-shot: play once, hold last frame
]

# startup animation: waving row, played once on first run
INTRO = ("waving", 3)


def spread_indices(items, cap):
    """Pick <= cap items spread across the list."""
    if len(items) <= cap:
        return items
    return [items[round(i * (len(items) - 1) / (cap - 1))] for i in range(cap)]


def to_rgb565(pix):
    r, g, b = pix[:3]
    v = ((r >> 3) << 11) | ((g >> 2) << 5) | (b >> 3)
    return v & 0xFF, v >> 8  # little-endian


def cell_frames(im, row):
    """Indices of non-empty columns in a row."""
    cols = []
    for col in range(GRID_COLS):
        cell = im.crop((col * CELL_W, row * CELL_H, (col + 1) * CELL_W, (row + 1) * CELL_H))
        if cell.getchannel("A").getextrema()[1] > 0:
            cols.append(col)
    return cols


def bake_card(sprite):
    """Compose the sprite over a rounded card on the screen bg, -> RGB."""
    card = Image.new("RGBA", (TARGET_W, TARGET_H), (0, 0, 0, 0))
    draw = ImageDraw.Draw(card)
    draw.rounded_rectangle((0, 0, TARGET_W - 1, TARGET_H - 1), CORNER_R, fill=CARD_COLOR + (255,))
    out = Image.new("RGBA", (TARGET_W, TARGET_H), SCREEN_BG + (255,))
    out.alpha_composite(card)
    out.alpha_composite(sprite)
    return out.convert("RGB")


def emit_frames(im, name, row, c_lines):
    """Generate <= MAX_FRAMES frames for a row; returns their symbol names."""
    cols = spread_indices(cell_frames(im, row), MAX_FRAMES)
    symbols = []
    for idx, col in enumerate(cols):
        cell = im.crop((col * CELL_W, row * CELL_H, (col + 1) * CELL_W, (row + 1) * CELL_H))
        sprite = cell.resize((TARGET_W, TARGET_H), Image.LANCZOS)
        rgb = bake_card(sprite)
        sym = f"pet_frame_{name}_{idx}"
        data = bytearray()
        for y in range(TARGET_H):
            for x in range(TARGET_W):
                data += bytes(to_rgb565(rgb.getpixel((x, y))))
        c_lines.append(
            f"const uint8_t {sym}_map[] = {{\n    " + ", ".join(f"0x{b:02x}" for b in data) + "\n};\n"
        )
        c_lines.append(
            f"const lv_image_dsc_t {sym} = {{\n"
            f"    .header.cf = LV_COLOR_FORMAT_RGB565,\n"
            f"    .header.magic = LV_IMAGE_HEADER_MAGIC,\n"
            f"    .header.w = {TARGET_W},\n"
            f"    .header.h = {TARGET_H},\n"
            f"    .header.stride = {TARGET_W * 2},\n"
            f"    .data_size = {len(data)},\n"
            f"    .data = {sym}_map,\n"
            f"}};\n"
        )
        symbols.append(f"&{sym}")
    return symbols


def emit(im, out_dir):
    h_lines = [
        "/* Auto-generated by tools/pet-assets/gen_frames.py — do not edit. */",
        "#pragma once",
        "",
    ]
    c_lines = [
        "/* Auto-generated by tools/pet-assets/gen_frames.py — do not edit. */",
        '#include "pet_frames.h"',
        "",
    ]
    anims = {}
    for state, row, loop in STATES:
        anims[state] = (emit_frames(im, state, row, c_lines), loop)
    intro_frames = emit_frames(im, INTRO[0], INTRO[1], c_lines)

    c_lines.append("const pet_state_anim_t pet_anims[PET_STATE_COUNT] = {")
    for state, _, _ in STATES:
        frames, loop = anims[state]
        c_lines.append(
            f"    [PET_STATE_{state.upper()}] = {{ .frames = {{{', '.join(frames)}}},"
            f" .count = {len(frames)}, .loop = {'true' if loop else 'false'} }},"
        )
    c_lines.append("};")
    c_lines.append("")
    c_lines.append(
        "const pet_state_anim_t pet_intro_anim = { .frames = {"
        + ", ".join(intro_frames)
        + "}, .count = " + str(len(intro_frames)) + ", .loop = false };"
    )

    h_lines.append('#include "pet_bridge.h"')
    h_lines.append('#include "lvgl.h"')
    h_lines.append("")
    h_lines.append("#define PET_FRAME_W 96")
    h_lines.append("#define PET_FRAME_H 104")
    h_lines.append("#define PET_MAX_FRAMES 4")
    h_lines.append("")
    h_lines.append("typedef struct {")
    h_lines.append("    const lv_image_dsc_t *frames[PET_MAX_FRAMES];")
    h_lines.append("    uint8_t count;")
    h_lines.append("    bool loop;")
    h_lines.append("    uint32_t frame_ms; // 0 = renderer default (150 ms)")
    h_lines.append("} pet_state_anim_t;")
    h_lines.append("")
    h_lines.append("extern const pet_state_anim_t pet_anims[PET_STATE_COUNT];")
    h_lines.append("extern const pet_state_anim_t pet_intro_anim; // waving row, one-shot")
    h_lines.append("")

    (out_dir / "pet_frames.h").write_text("\n".join(h_lines))
    (out_dir / "pet_frames.c").write_text("\n".join(c_lines))
    print(f"wrote {out_dir/'pet_frames.h'}, {out_dir/'pet_frames.c'}")


def main():
    im = Image.open(sys.argv[1]).convert("RGBA")
    assert im.size == (1536, 1872), f"unexpected spritesheet size {im.size}"
    emit(im, Path(sys.argv[2]))


if __name__ == "__main__":
    main()
